# Listar Todas
GET http://localhost:8080/api/task
#Authorization: Basic user 711e36f3-3952-4424-b7aa-97043923193f

###

# Apagar
DELETE http://localhost:8080/api/task/1

###

# Cadastrar
POST http://localhost:8080/api/task
Content-Type: application/json
Authorization: Basic joao@fiap.com.br 123

{
      "title": "Modelar BD",
      "description": "modelar tabelas do banco",
      "score": 150
}
###


# Listar usuários
GET http://localhost:8080/api/user

###

# Detalhes do usuário
GET http://localhost:8080/api/user/1

###

# Apaga usuário
DELETE http://localhost:8080/api/user/1
Authorization: Basic admin@fiap.com.br administrador
###

# Cadastrar usuário
POST http://localhost:8080/api/user/
Authorization: Basic admin@fiap.com.br administrador
Content-type: application/json

{
      "name": "João Carlos Lima",
      "email": "joao@fiap.com.br",
      "password": "123"
}
###

# Alterar usuário
PUT http://localhost:8080/api/user/1
Authorization: Basic admin@fiap.com.br administrador
Content-type: application/json

{
      "name": "Maria Pereira",
      "email": "maria@fiap.com.br",
}
###